addSbtPlugin("org.scalameta"             % "sbt-scalafmt"              % "2.4.2")
addSbtPlugin("ch.epfl.scala"             % "sbt-bloop"                 % "1.4.4")
addSbtPlugin("pl.project13.scala"        % "sbt-jmh"                   % "0.4.0")
addSbtPlugin("com.github.cb372"          % "sbt-explicit-dependencies" % "0.2.13")
addSbtPlugin("io.github.davidgregory084" % "sbt-tpolecat"              % "0.1.13")
